# Generated by Django 5.0.6 on 2025-09-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='created_by',
            new_name='created_user_id',
        ),
    ]
