# Generated by Django 5.0.6 on 2025-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0002_rename_created_by_partners_created_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
