# Generated by Django 5.0.6 on 2025-09-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0003_alter_partners_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
