# Generated by Django 5.0.6 on 2025-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0004_alter_partners_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
