# Generated by Django 4.2.2 on 2025-11-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matrix', '0005_partners_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_image',
        ),
    ]
