# Generated by Django 4.2.2 on 2025-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserChat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', models.JSONField()),
            ],
        ),
    ]
