# Generated by Django 4.2.2 on 2025-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserChat', '0002_mydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
